### ISSUE TITLE
countdown.module.d.ts using angular 11

### ISSUE THREAD

**Issue by hosamhemaily** [cipchk/ngx-countdown#101]
i have an error in countdown.module.d.ts file 
has no exported member 'ɵɵInjectorDeclaration'
i spent 4 hours and still not fixed 

![image](https://user-images.githubusercontent.com/31744225/121865632-7add1200-ccfe-11eb-9eea-6856b11b3057.png)

**Comment by hosamhemaily** [comment]
i am using angular 11

**Comment by cipchk** [comment]
Pls use `11.0.3` version in angular 11.
