### ISSUE TITLE
Display countdown in only seconds format

### ISSUE THREAD

**Issue by Araknos** [cipchk/ngx-countdown#103]
Hello,

Is there a way to format the countdown in a only seconds format ?
Instead of 2:00 (mm:ss) => 120 (?)

**Comment by cipchk** [comment]
@Araknos Yes, you can via `formatDate `, like this: https://github.com/cipchk/ngx-countdown/issues/49#issuecomment-561989905

**Comment by Araknos** [comment]
@cipchk thank you, do you have any demo of formatDate ?

**Comment by cipchk** [comment]
Like this:

```ts
  config: CountdownConfig = {
    leftTime: 60 * 3,
    formatDate: ({ date }) => `${date / 1000}`,
  };
```
