### ISSUE TITLE
node_modules/ngx-countdown/countdown.component.d.ts:19:9 - error TS1086: An accessor cannot be declared in an ambient context

### ISSUE THREAD

**Issue by tussharkhairnar** [cipchk/ngx-countdown#109]
ERROR in node_modules/ngx-countdown/countdown.component.d.ts:18:9 - error TS1086: An accessor cannot be declared in an ambient context.

18     set config(i: CountdownConfig);
           ~~~~~~
node_modules/ngx-countdown/countdown.component.d.ts:19:9 - error TS1086: An accessor cannot be declared in an ambient context.

19     get config(): CountdownConfig;
           ~~~~~~

**Comment by cipchk** [comment]
@tussharkhairnar  Please tell which angular version you are currently?

**Comment by SabikAbtahee** [comment]
I had the same issue in Angular: 8.2.9. I Installed "ngx-countdown": "^8.0.4" and it solved the issue.
