### ISSUE TITLE
How can I change the config during runtime?

### ISSUE THREAD

**Issue by elementalTIMING** [cipchk/ngx-countdown#111]
Hi there,

the countdown work really well. But how can I change some configuration settings and restart the countdown?

Scenario:
initially I start the countdown with a config like this:

	public countdownConfig = { leftTime: 60, format: 'mm:ss', demand: true };

Works great with `begin()`. But for a second run I like to modify the `leftTime`. So I do something like:

	this.countdownConfig.leftTime = 100;
	this.countdown.restart()

The problem is that the configuration is being ignored and the old `leftTime` value is used. How can I modify the configuration?

Thx for your help,
Lars

**Comment by cipchk** [comment]
A [demo](https://stackblitz.com/edit/ngx-countdown-setup-jrepix):

```ts
import { Component } from '@angular/core';
import { CountdownConfig } from 'ngx-countdown';

@Component({
  selector: 'my-app',
  template: `
  <p>
  <button type="button" (click)="cd.begin()">Begin</button>
  <button type="button" (click)="changeConfig()">Change Config</button>
  </p>
  <countdown #cd [config]="countdownConfig"></countdown>

  `,
})
export class AppComponent {
  countdownConfig: CountdownConfig = {
    leftTime: 60,
    format: 'mm:ss',
    demand: true,
  };

  changeConfig(): void {
    this.countdownConfig = { leftTime: 160, format: 'mm:ss', demand: true };
  }
}
```

**Comment by elementalTIMING** [comment]
> demo

@cipchk thx for the demo. Indeed it works when I set a **complete** new config object. But why isn't it possible to modify just a **single property**?

**Comment by cipchk** [comment]
In order to get better performance, ngx-countdown component are running under `OnPush` mode, this means any mutate to the `@Input()` data won't trigger change detection, please use immutable way to update array or object.

**Comment by elementalTIMING** [comment]
> In order to get better performance, ngx-countdown component are running under `OnPush` mode, this means any mutate to the `@Input()` data won't trigger change detection, please use immutable way to update array or object.

Thx, I understand. Wouldn't it then not be a good idea to provide an `update()` method for the countdown to force the change detection?

**Comment by cipchk** [comment]
A kind of magic:

```ts
this.countdownConfig = { ...this.countdownConfig, leftTime: 160 };
```

**Comment by elementalTIMING** [comment]
> A kind of magic:
> 
> ```ts
> this.countdownConfig = { ...this.countdownConfig, leftTime: 160 };
> ```

You're so right! Sometimes it can be so easy.... I was so focused that I didn't see the simplest things. Thx!

**Comment by elementalTIMING** [comment]
> A kind of magic:
> 
> ```ts
> this.countdownConfig = { ...this.countdownConfig, leftTime: 160 };
> ```

It looked so easy but it isn't :-( 
The countdown UI changes. That's fine! But now the countdown wont start again after `restart(); begin()`. It doesn't matter in which way I modify the configuration. Do you have any idea?

**Comment by elementalTIMING** [comment]
it is necessary not for modify the the `config` but the component config like below:

	<countdown #cd ...>

	this.cd.config = { ...this.cd.config, leftTime: 100 };

That works but it's not really nice...

**Comment by cipchk** [comment]
```ts
this.countdownConfig = { ...this.countdownConfig, leftTime: 160, demand: false };
```

**Comment by elementalTIMING** [comment]
> ```ts
> this.countdownConfig = { ...this.countdownConfig, leftTime: 160, demand: false };
> ```

Not really, because I need the `demand: true` for manual control.

**Comment by cipchk** [comment]
Original configuration:

```ts
public countdownConfig = { leftTime: 60, format: 'mm:ss', demand: true };
```

Start immediately after change:

```ts
this.countdownConfig = { ...this.countdownConfig, leftTime: 160, demand: false };
```

Start manually after change:

```ts
this.countdownConfig = { ...this.countdownConfig, leftTime: 160 };
```
