### ISSUE TITLE
ERROR in src/app/shared/shared.module.ts(55,3): error TS2741: Property 'locale' is missing in type '{ format: string; }' but required in type 'CountdownGlobalConfig'.

### ISSUE THREAD

**Issue by hanslbua** [cipchk/ngx-countdown#112]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ x ] Bug report -> please search issues before submitting
[ ] Feature request
[ x ] Documentation issue or request
</code></pre>

## Current behavior
getting below error
ERROR in src/app/shared/shared.module.ts(55,3): error TS2741: Property 'locale' is missing in type '{ format: string; }' but required in type 'CountdownGlobalConfig'.

function countdownConfigFactory(): CountdownGlobalConfig {
return { format: mm:ss };
}

## Environment

<pre><code>
Angular version: 13.2.0

ngx-countdown version: 13.0.0
</code></pre>

i found this issue in list, but there is no solution giving:
https://github.com/cipchk/ngx-countdown/issues/76

**Comment by cipchk** [comment]
Can you provide the definition of `CountdownGlobalConfig`?

**Comment by hanslbua** [comment]
```
export declare class CountdownGlobalConfig implements CountdownConfig {
    private locale;
    constructor(locale: string);
    demand?: boolean;
    leftTime?: number;
    format?: string;
    timezone?: string;
    formatDate?: CountdownFormatFn;
    static ɵfac: i0.ɵɵFactoryDeclaration<CountdownGlobalConfig, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<CountdownGlobalConfig>;
}
```

**Comment by cipchk** [comment]
I'm not sure where the `CountdownGlobalConfig` come from, but at least the `countdownConfigFactory` return value must conform to that definition.

This problem is not caused by `ngx-countdown`.

**Comment by hanslbua** [comment]
Well. The CountdownGlobalConfig comes from [ngx-countdown](https://github.com/cipchk/ngx-countdown)/[lib](https://github.com/cipchk/ngx-countdown/tree/master/lib)/[src](https://github.com/cipchk/ngx-countdown/tree/master/lib/src)/countdown.config.ts

**Comment by cipchk** [comment]
Sorry, my mistake, this is docs typo, pls using: 

```diff
- function countdownConfigFactory(): CountdownGlobalConfig {
+ function countdownConfigFactory(): CountdownConfig {
```
