### ISSUE TITLE
Supported versions of Angular aren't mentioned

### ISSUE THREAD

**Issue by CallumOak** [cipchk/ngx-countdown#113]
I can't find anywhere that mentions which versions of the countdown is compatible with which versions of Angular.
I couldn't get it to work with Angular 11, then tried it with angular 13 and it worked, but I wish the readme or another place would mention compatibility

**Comment by cipchk** [comment]
Await for https://github.com/angular-eslint/angular-eslint/pull/1004

**Comment by cipchk** [comment]
Full version list https://www.npmjs.com/package/ngx-countdown?activeTab=versions

**Comment by CallumOak** [comment]
Are those the versions of ngx countdown or of Angular? 
What I'm not seeing is something saying "version X of ngx-countdown supports versions A, B, ... of Angular"

**Comment by cipchk** [comment]
Always follow major Angular versions, e.g. Angular 11 or ngx-countdown 11.
