### ISSUE TITLE
The countdown does not start when the parent is in OnPush

### ISSUE THREAD

**Issue by GitHubish** [cipchk/ngx-countdown#120]
I call the countdown in a parent whose change detection is onPush. My Component that creates the countdown sets the remaining time assynchronously. When I call the begin() method the countdown does not start 

Example : [stackblitz](https://stackblitz.com/edit/angular-d7raey?file=src/my-child/my-child.component.ts)

I don't understand why it doesn't work

**Comment by GitHubish** [comment]
If I set `demand: false` it works but if I change the config and set `demand: true` it doesn't work again. And I can't see in the code why. Do you have an idea @cipchk ?

**Comment by cipchk** [comment]
```diff
- this.config = { ...this.config, leftTime: 160 };
+ this.config = { ...this.config, leftTime: 160, demand: false };
```
