### ISSUE TITLE
Finish event not firing

### ISSUE THREAD

**Issue by newkillerbeast2017** [cipchk/ngx-countdown#13]
@cipchk  I am trying to fire an `onfinished` event when the countdown gets over. Here is what my html looks like:

`<countdown class="timer" [config]="config" (finished)="finishTest()">$!m!:$!s!</countdown>`

The only issue is that the event if fired as soon as the component is loaded. In simple terms, if i kept the config as 10 seconds timer but the finished event is fired in 1st second itself. Any idea what is going wrong and also what other info can I provide for further help?

**Comment by cipchk** [comment]
Sorry,  i can't understand what you saying, i create a online [demo](https://stackblitz.com/edit/ngx-countdown-setup-heks4b?file=app/app.component.ts) further explanation.

**Comment by Ankit199** [comment]
this is not working with angular 8 .. I am also facing same issue .
ngx-countdown (finished) event is not firing

**Comment by OldManSmithers** [comment]
Can confirm this is still an issue with Angular 7.  The finished event is never firing, though normal events seem to still be working and you can work with those.  A workaround for those still having an issue with the finished event:

HTML: 
`<countdown #countdown [config]="{leftTime: 5, demand: false}" (event)="timesUp($event)">$!h!:$!m!:$!s!</countdown>`

TS:
`timesUp(event) {
    if (event.action == "done") {
      console.log("Finished");
    }  
  }`

**Comment by LuisPeregrinaPSL** [comment]
In the demo you used angular 5. As of now Angular is in version 9.

In the documentation you have a (done) event, not even that is being triggered. Which brings the issue that the doc says (done) instead of (finished).

**Comment by revzo** [comment]
> Can confirm this is still an issue with Angular 7. The finished event is never firing, though normal events seem to still be working and you can work with those. A workaround for those still having an issue with the finished event:
> 
> HTML:
> `<countdown #countdown [config]="{leftTime: 5, demand: false}" (event)="timesUp($event)">$!h!:$!m!:$!s!</countdown>`
> 
> TS:
> `timesUp(event) { if (event.action == "done") { console.log("Finished"); } }`

Thanks, working Angular v10 rc! :)

**Comment by Ankit199** [comment]
Hi Daniel ,

It's working fine.

Thanks for support

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
