### ISSUE TITLE
How to reset the countdown again revisit the page

### ISSUE THREAD

**Issue by dhanarajp** [cipchk/ngx-countdown#14]
Hi, 
how to reset the countdown if again revisit the page.

**Scenario:**
_configured: 60sec_
1. Once login the page, countdown start
2. after 60sec automatically logout
3. try to login again the page, but countdown not restart

**Comment by cipchk** [comment]
When the target component is destroyed, i think can work. otherwise, just call `restart()` or `resume()` again.

**Comment by belall-shaikh** [comment]
I think the issue is still present in 3.0.1

**Comment by belall-shaikh** [comment]
check at https://stackblitz.com/edit/ngx-countdown-issue
steps to reproduce
1- view timer route
2- wait till time finishes.
3- revisit the route

you will see that the timer doesn't start unless the page is refreshed.

**Comment by belall-shaikh** [comment]
I was able to fix this by calling the counter restart in a setTimeout method in ngOnInit

setTimeout(() => this.counter.restart());

**Comment by belall-shaikh** [comment]
I have updated the example:  https://stackblitz.com/edit/ngx-countdown-issue
