### ISSUE TITLE
restart not working

### ISSUE THREAD

**Issue by xbu** [cipchk/ngx-countdown#17]
need to restart the timer when finished,  restart method not work in finished event.
but worked when I fired a button click event.

demo https://stackblitz.com/edit/ngx-countdown-setup-asxjxk?file=app%2Fapp.component.html

**Comment by cipchk** [comment]
i think not bug, will be destroy after `finished` of the event triggered. so you can use `setTimeout` changed exection order, link this https://stackblitz.com/edit/ngx-countdown-setup-qd6z37?file=app/app.component.ts

**Comment by Shubhasis10** [comment]
Working in angular 9
