### ISSUE TITLE
About Language ?

### ISSUE THREAD

**Issue by paragyelonde** [cipchk/ngx-countdown#18]
How do i change the language of countdown to English..???

**Comment by cipchk** [comment]
What do you mean?

**Comment by ududsha** [comment]
Check the example here: you will figure it out.
https://cipchk.github.io/ngx-countdown/#/

**Comment by satanand7** [comment]
I mean i want this in english.

**Comment by Brohus** [comment]
@satanand7  did you figure it out??

**Comment by Brohus** [comment]
@paragyelonde did you figure it out??
