### ISSUE TITLE
ngx-countdown error when using with angular 6.0.0

### ISSUE THREAD

**Issue by rajpat** [cipchk/ngx-countdown#19]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
build errors when compiling with latest version of angular version 6.0

ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-countdown/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

## Expected behavior
ngx-coundown not compatible with Angular version 6.0 and should work without any changes.

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:
OS: OSX on mac, node 8.11.

**Comment by hectorccmx** [comment]
Same issue here, I think it's beacuse current version depends on angular 5.2.0.

**Comment by cipchk** [comment]
coming soon

**Comment by hectorccmx** [comment]
Could you tell us when you spect to release a bug fix? This is not pressure, we need to know in order to make a decision. Thanks in advance
