### ISSUE TITLE
ngx-countdown@1.0.1 requires a peer of @angular/common@4.0.1 but none was installed.

### ISSUE THREAD

**Issue by acuntex** [cipchk/ngx-countdown#2]
If you use the current version of angular, you get the following error in NPM:

```
+-- UNMET PEER DEPENDENCY @angular/common@4.3.6
+-- UNMET PEER DEPENDENCY @angular/core@4.3.6
ngx-countdown@1.0.1 requires a peer of @angular/common@4.0.1 but none was installed.
ngx-countdown@1.0.1 requires a peer of @angular/core@4.0.1 but none was installed.
```

Any chance you could fix and update the dependencies? Thanks!

**Comment by cipchk** [comment]
bug confirmed, today fix this. thinks.

**Comment by cipchk** [comment]
see [1.0.2](https://github.com/cipchk/ngx-countdown/blob/master/CHANGELOG.md).

**Comment by acuntex** [comment]
Thanks for your quick response! 👍
