### ISSUE TITLE
Refresh component after lefttime update

### ISSUE THREAD

**Issue by jma-9code** [cipchk/ngx-countdown#22]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[X ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Update config.lefttime, component not refreshed

## Expected behavior
Update config.lefttime, component updated

## Environment

<pre><code>
Angular version: 6.0.0
ngx-countdown version: latest
Browser:
- [ X] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:
</code></pre>

**Comment by cipchk** [comment]
Yes.

A temporary solution changed time value via `config` parameter.

**Comment by jma-9code** [comment]
If you change the config.lefttime parameter, you need to refresh the page to see the new value applied.

**Comment by cipchk** [comment]
Please try to reproduce via https://stackblitz.com/edit/ngx-countdown-setup, thanks!

**Comment by jma-9code** [comment]
https://stackblitz.com/edit/ngx-countdown-setup-fuu7r7

**Comment by cipchk** [comment]
A working [demo](https://stackblitz.com/edit/ngx-countdown-setup-gcmdyf?file=src/app/app.component.ts)
