### ISSUE TITLE
How can i get the current count down time to program the other functions?

### ISSUE THREAD

**Issue by phuong-dut-es** [cipchk/ngx-countdown#23]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-countdown version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
sorry, just only via `notify` parameter.

duplcated of #16
