### ISSUE TITLE
Counting step is 2 rather than 1

### ISSUE THREAD

**Issue by mohsen69** [cipchk/ngx-countdown#29]
Hello .

When counter starts , the seconds decreased 2 by 2.
Even when i use demo sample in my project.

how can i fix it?

here is markup
`<countdown [config]="{leftTime: 1000 * 10}">$!m!:$!s!</countdown>`

in other word
decrease speed is faster than 1 second

**Comment by cipchk** [comment]
Sorry, i don't understand what you mean, but i confirm working via `leftTime`.

![demo](https://user-images.githubusercontent.com/2987467/50587421-dad9f800-0eb8-11e9-8dbe-ed301126fd27.gif)

**Comment by mohsen69** [comment]
Thanks. When i moved sample to another component , counter worked correctly.

**Comment by carol-braileanu** [comment]
I am having the same problem. Did you figure out the cause?

**Comment by HansDaigle** [comment]
Same issue here

**Comment by pedcru** [comment]
You must set leftTime > 0 and then it works fine.

**Comment by leonardlib** [comment]
You must set **leftTime > 0** and then it works fine.
