### ISSUE TITLE
How can i get it in english.

### ISSUE THREAD

**Issue by satanand7** [cipchk/ngx-countdown#30]
I don't understand this language. How can i get it in English.

**Comment by cipchk** [comment]
duplcated of #18 , but i don't know what the meaning of "language" means?

**Comment by IraErshova** [comment]
@cipchk Could you please delete hieroglyphs from the template:
Because it affects all people who want to use your package but couldn't because of  hieroglyphs

```template:  '$!h!时$!m!分$!s!秒',```

**Comment by IraErshova** [comment]
See what I meant in my comment above
![screenshot from 2019-02-06 13-00-25](https://user-images.githubusercontent.com/14790520/52337065-40b52480-2a0f-11e9-9a0a-f7888e414cd1.png)
