### ISSUE TITLE
error in  '@angular/core' 

### ISSUE THREAD

**Issue by ghost** [cipchk/ngx-countdown#31]
WARNING in ./node_modules/ngx-countdown/fesm5/ngx-countdown.js
85:38-54 "export 'defineInjectable' was not found in '@angular/core'

**Comment by cipchk** [comment]
Pls check your angular version is `6` or `7` in local project, If using `2.1.0` version when angular version is `5`.

**Comment by ghost** [comment]
thanks

**Comment by Klanders85** [comment]
The app I'm building(which is using ngx-countdown) is being written in Angular 6. I am using ngx-countdown version 3.1.0. All of this is being packaged up as a library and dropped into another Angular app that uses version 5. Everything was working fine on Friday, and now I'm getting the same error mentioned above...

Any ideas or direction you could point me in? Thanks!

**Comment by cipchk** [comment]
@Klanders85 The global configuration feature has been added in 3.2.0 and uses `@Injectable({ providedIn: 'root' })` as the scope, which is an option supported by angular `6` or `7`.

so, you can try to fix it to the `3.1.0` version.

**Comment by Klanders85** [comment]
That fixed the issue. Thank you for the help @cipchk!

**Comment by NithyaSaamy** [comment]
WARNING in ./node_modules/ngx-countdown/fesm5/ngx-countdown.js 107:44-62
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

im getting this error, when i imported this import { CountdownModule } from 'ngx-countdown'; in app module.ts

**Comment by cipchk** [comment]
@NithyaSaamy Duplcated of #56
