### ISSUE TITLE
Timer (forward) instead of countdown

### ISSUE THREAD

**Issue by bogacg** [cipchk/ngx-countdown#32]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Time counts down

## Expected behavior

Option to make timer counts time forward (till an end point, minutes or Unix ms in future)

I liked this component, good job, however it would be even better if we could have an option to count time forward.

**Comment by sudharsan203** [comment]
i am facing same issue here, #32

**Comment by bejgumshirisha** [comment]
Resolved somewhat this issue by modifying code
I created a new input variable in ConfigTimer interface to check the type of countdown required

Modified Init Method as 
 if(me.config.countType == 'forward'){
      me.isCountDown = true;
    }
    else{
      me.isCountDown = false;
    }
Modified reflow method as follows :
if(me.isCountDown){
      //this code for count up
     me.left = me.left + me.frequency * count;
    }
    else{
//this code for count-down
    me.left = me.left - me.frequency * count;
    }

It is working fine.It Works for both forward as well as downward.

But I have small problem with this.When time crosses the 24hrs then it is getting reset.I want to increment the time after reaching a days also like it is working in count-down clock configuration.

Working around for that.If i finishes I will update it
