### ISSUE TITLE
Countdown to events coming in more than 100 days is displayed incorrectly

### ISSUE THREAD

**Issue by iSerganov** [cipchk/ngx-countdown#33]
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request

## Current behavior
As far as I understand, for the moment maximum supported time gap for countdown is 100 days. If I need to countdown for a certain time that will occur later than in 100 days, the first number won't be displayed. E.g. using the following template : $!d!:$!h!:$!m!:$!s! for date and time in 215 days will give me:
15:00:00:00 instead of 215:00:00:00

## Expected behavior
Usage of the following template : $!d!:$!h!:$!m!:$!s! for date and time in 215 days should produce the following displayed value:
215:00:00:00

## Environment

Angular version: 7.2.8
ngx-countdown version: 3.2.0
Browser:
- [x] Chrome (desktop) version 72
- [x] Firefox version

**Comment by riponghosh** [comment]
Hi. You can config as you wise.
`<countdown [config]="{leftTime: 359994990.9, clock: ['d', 100, 2, 'h', 100, 2, 'm', 60, 2, 's', 60, 2, 'u', 10, 1] }">$!d!:$!h!:$!m!:$!s!</countdown>`
here 'd', 100, 2, means day calculate range is 100 and show digit is 2.
so change the date range and show digit number as you wise.
Like
`<countdown [config]="{leftTime: 359994990.9, clock: ['d', 1000, 3, 'h', 100, 2, 'm', 60, 2, 's', 60, 2, 'u', 10, 1] }">$!d!:$!h!:$!m!:$!s!</countdown>`

**Comment by pockata-kt** [comment]
**Please!** Document how exactly can we configure the timer. I wanted to show the remaining time, but only show seconds and minutes (hours and days to be added to the minutes). It was extremely hard for me to figure out how I should do that and I'm still not sure I did it the right way.

**Comment by riponghosh** [comment]
> **Please!** Document how exactly can we configure the timer. I wanted to show the remaining time, but only show seconds and minutes (hours and days to be added to the minutes). It was extremely hard for me to figure out how I should do that and I'm still not sure I did it the right way.

You can config like,
<countdown [config]="{leftTime: 360000, clock: ['m', 1000000, 5, 's', 60, 2, 'u', 10, 1]}"> $!m! Minutes $!s-ext! second</countdown>

here 'm', 1000000, 5, means Minutes calculate range is 1000000 and show digit is 5.
The leftTime will show in Minutes and second.

**Comment by pockata-kt** [comment]
Is there any way possible to not show the leading zeros and still be able to show big numbers?
I.e. when there are 100 minutes left to show `100:00`, and when there is 5 minutes left to show `5:00`, not `005:00`?
