### ISSUE TITLE
Remove the first zero?

### ISSUE THREAD

**Issue by nektobit** [cipchk/ngx-countdown#34]
Hello everyone, did not find this in the documentation. Is it possible to remove the first zero if I have the line '01 day 05 hours' to make '1 day 5 hours' ?

**Comment by ghost** [comment]
Did you figure this out? I'm trying to do the same thing.

**Comment by nektobit** [comment]
@jackparkerop i am migrate to another solution

**Comment by fromage9747** [comment]
@nektobit What solution did you migrate to?  I am facing the same issue.  I want to remove the first zero.

**Comment by nektobit** [comment]
Hi @fromage9747 i am use this:
https://www.npmjs.com/package/ngx-moment,

**Comment by fromage9747** [comment]
@nektobit Thanks for that.  Just to confirm, ngx-moment is just a date manipulator, not a countdown timer, correct?  How are you using it as a countdown timer?  Or does your requirement for your app not need it to be a timer?

**Comment by nektobit** [comment]
@fromage9747 I use it to display the string 'Uptime: 6 minutes' (amDuration pipe)
if you need only seconds coundown you can use 

```
  timer;
  time: number = 5;
  startCountdown(seconds) {
    let counter = seconds;

    this.timer = setInterval(() => {
      this.time = counter;
      counter--;

      if (counter < 0) {
        clearInterval(this.timer);
        // do something
      }
    }, 1000);
  }
```
and {{ time }} in your template

**Comment by fromage9747** [comment]
@cipchk Does this mean that this is now included in the next build/release?

**Comment by cipchk** [comment]
@fromage9747 Yes, you can see such an example in [Custom format date](https://cipchk.github.io/ngx-countdown/#/)
