### ISSUE TITLE
Timer does not update value if option demand is true

### ISSUE THREAD

**Issue by kristiWabion** [cipchk/ngx-countdown#38]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[X ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

The timer does not update the its value if it is stopped( demand true).
Current config  
```
<countdown class="text-lg" [config]="{leftTime: config[key].shutdownTimer, demand: true}">
 $!h!:$!m!:$!s!</countdown>
```
When the variable shutdownTimer changes the value the timer does not reflect this change. If the option "demand is false" and the same action occurs  than it updates correctly showing the new value.

## Expected behavior

Timer should update the value and show the most recent one even when option demand is true.

## Environment

<pre><code>
Angular version: 7.2.6

ngx-countdown version: 3.2.0

Browser:
- [X ] Chrome (desktop) version 75.0.3770.142
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
According to [Angular documentation](https://angular.io/guide/lifecycle-hooks#onchanges)，should be not use change a proerty value, you can change the `config` pass to full object.

**Comment by kristiWabion** [comment]
Hello @cipchk , 
Thank you for the answer. I changed the config as below
`
<countdown class="text-lg" [config]=timerObj[key].config>
$!h!:$!m!:$!s!/countdown>
`
but I am still having the same problem. I think the problem is more related with the option "demand: true". Do you have any other suggestion that I can check? 
Regards
Kristi

**Comment by cipchk** [comment]
A simple demo: https://stackblitz.com/edit/ngx-countdown-setup-nvf7kk?file=src/app/app.component.ts

**Comment by kristiWabion** [comment]
@cipchk Thank you for the demo. Can you try to change the value of demand to **true** on this method?
`
change(): void {
    this.timerObj = {
      t1: {
        config: {
          leftTime: 20,
          demand: true,
        }
      }
    }
  }
`
The timer will not update as I stated.

**Comment by cipchk** [comment]
Yes, you muse call `begin()` method, like this:

```html
<countdown #cd1 [config]="timerObj.t1.config"> $!h!:$!m!:$!s!</countdown>
<button (click)="cd1.begin()">Via begin()</button>
```

**Comment by kristiWabion** [comment]
@cipchk What I need is a way on how to update the timer value before it is running.
So if the timer is showing 02:00 I want to increment the value to 04:00 and then start the countdown.
What is happening right now is that when I increment the value the timer still shows 02:00, but when I start the timer it shows 03:59 ... ,so I guess the timer only gets the update when its started.
Is there any way how to make the timer update the value while its stopped?

**Comment by cipchk** [comment]
@kristiWabion Sorry, not support increment or decrement operator.

But you can change the `config` property in running to soloved it, like this:

```ts
  change(): void {
    this.timerObj = {
      t1: {
        config: {
          leftTime: 20,
          demand: false,
        }
      }
    }
  }
```

**Comment by kristiWabion** [comment]
@cipchk Thank you. Would be great to have this feature in the future.
