### ISSUE TITLE
Asian characters

### ISSUE THREAD

**Issue by SilinaGeorge** [cipchk/ngx-countdown#40]
Is there a way to get rid of the Asian characters? This is my code

`<countdown [config]="{leftTime: 10}" #cd1 (finished) ="timerFinished()"></countdown>
<button (click)="cd1.pause()" class="btn btn-link btn-sm">pause</button>
<button (click)="cd1.resume()" class="btn btn-link btn-sm">resume</button>
<button (click)="cd1.restart()" class="btn btn-link btn-sm">restart</button>`

and this is how my counter looks: 00时00分00秒

I am using Angular 8, Chrome.

**Comment by belall-shaikh** [comment]
How did you fix this.

**Comment by SilinaGeorge** [comment]
I think there are two ways of doing it, I'm not too sure about this first one I didnt try it, in the config you use the format tag. You can find more about it in the readme file. I did it like this
``` <countdown class="text-lg"  (finished)="timerFinished()" [config]="config"> $!h!:$!m!:$!s!</countdown>```
