### ISSUE TITLE
Not working with angular 8

### ISSUE THREAD

**Issue by zerr0s** [cipchk/ngx-countdown#41]
Hello, forgive me for my bad english.

I can't get working ngx-countdown with angular 8. Typescripts like OK, but when calling the page, an error append:

`TypeError: Cannot read property 'stop' of undefined`

```js
import { Component, OnInit, ViewChild, ViewEncapsulation } from '@angular/core';
import { CountdownComponent } from 'ngx-countdown';

@Component({
  selector: 'app-live-page',
  templateUrl: './live-page.component.html',
  styleUrls: ['./live-page.component.css'],
  encapsulation: ViewEncapsulation.None,
  providers: []
})
export class LivePageComponent implements OnInit {
  duration: number: 0;
  @ViewChild('countdown', {static: false}) counter: CountdownComponent;

  constructor(
  ) { }

  ngOnInit() {
    this.duration = 3600; // test
    this.counter.stop(); // test
  }
}
```
```html
<span><countdown [config]='{leftTime: duration}'>$!h!:$!m!:$!s!</countdown></span>
```
Any idea to get it working please ?

Thanks.

**Comment by cipchk** [comment]
Should be specified template variable, like this:

```html
<countdown #countdown [config]='{leftTime: duration}'>$!h!:$!m!:$!s!</countdown>
```

And `{static: false}` muse be using `{static: true}`, pls refer to https://angular.io/guide/static-query-migration

**Comment by zerr0s** [comment]
Hi, I don't understand the answer. I do not have problem to run the countdown using  angular 8, the problem is that all functions to control the timer are KO with an error like:

> TypeError: Cannot read property 'stop' of undefined

I've changed from false to true for viewchild but still the same problem.

```
stop() { this.counter.stop(); }
start() { this.counter.start(); }
resume() { this.counter.resume(); }
restart() { this.counter.restart(); }
```
TS saying for start:

> ERROR in src/app/components/live-page/live-page.component.ts(78,5): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'EventEmitter<{}>' has no compatible call signatures.

**Comment by cipchk** [comment]
@zerr0s can you provider a reproduce via https://stackblitz.com/edit/ngx-countdown-setup (fork this)
