### ISSUE TITLE
cannot use methods

### ISSUE THREAD

**Issue by zerr0s** [cipchk/ngx-countdown#44]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ X ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

No methods works (begin, stop, resume, pause, etc.).

> ERROR
Error: Cannot read property 'begin' of undefined
> ERROR
Error: Cannot read property 'stop' of undefined

If these methods are put in a setTimeout, it works !! Can you explain me that please ? See below for an online test.

## Environment

<pre><code>
Angular version: 8.2.2

ngx-countdown version: 8.0.0

Browser:
- [ X ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

Test it at: [https://stackblitz.com/edit/ngx-countdown-setup-uff71k](https://stackblitz.com/edit/ngx-countdown-setup-uff71k)

**Comment by cipchk** [comment]
@zerr0s According the angular lifecycle, you can only actually trigger in `AfterViewInit` event.
