### ISSUE TITLE
error: export 'ɵɵinject' | 'ɵɵdefineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by augustotmw** [cipchk/ngx-countdown#46]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
I install and just put the plugin to work in project (importing on module and adding the tag on html).

When I compile, its showing me two warnings:

<pre><code>
WARNING in ./node_modules/ngx-countdown/fesm5/ngx-countdown.js
96:150-158 "export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/ngx-countdown/fesm5/ngx-countdown.js
96:44-62 "export 'ɵɵdefineInjectable' was not found in '@angular/core'
</code></pre>

And when I load it on browser it shows me:

<pre><code>

Uncaught TypeError: Object(...) is not a function
    at ngx-countdown.js:96
    at Object../node_modules/ngx-countdown/fesm5/ngx-countdown.js (ngx-countdown.js:103)
    at __webpack_require__ (bootstrap:81)
    at Object../src/app/app.module.ngfactory.js (app.effects.ts:8)
    at __webpack_require__ (bootstrap:81)
    at Object../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:81)
    at Object.0 (main.ts:29)
    at __webpack_require__ (bootstrap:81)
    at checkDeferredModules (bootstrap:43)

line 96:

CountdownGlobalConfig.ngInjectableDef = ɵɵdefineInjectable({ factory: function CountdownGlobalConfig_Factory() { return new CountdownGlobalConfig(ɵɵinject(LOCALE_ID)); }, token: CountdownGlobalConfig, providedIn: "root" });

</code></pre>

## Expected behavior

Work as it is in examples.

## Environment

Angular version: 

<pre><code>
Angular CLI: 6.1.2
Node: 10.15.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.2
@angular-devkit/core         0.7.2
@angular-devkit/schematics   0.7.2
@schematics/angular          0.7.2
@schematics/update           0.7.2
rxjs                         6.2.2
typescript                   2.7.2

</code></pre>

From dependencies object in `package.json`:
<pre><code>
        "@angular/animations": "^7.2.2",
        "@angular/cdk": "^7.1.1",
        "@angular/common": "^7.1.1",
        "@angular/compiler": "^7.1.1",
        "@angular/core": "^7.1.1",
        "@angular/forms": "^7.1.1",
        "@angular/http": "^7.1.1",
        "@angular/platform-browser": "^7.1.1",
        "@angular/platform-browser-dynamic": "^7.1.1",
        "@angular/router": "^7.1.1",
</code></pre>

ngx-countdown version: 8.0.0

Browser:
- [x] Chrome (desktop) version 76.0.3809.132

Others:

Great plugin! Hope I can make it works too. :)

**Comment by cipchk** [comment]
the `8.x` version only support angular8, pls refer to [abort `defineInjectable` description](https://github.com/angular/angular/issues/30413#issuecomment-491531239). 

you can tring `3.x` version.

**Comment by augustotmw** [comment]
Thats it! Work perfectly. Thanks a lot! 😄

Congratulations and thanks for this amazing work. 😊👏👏👏

[v 3.1.0](https://github.com/cipchk/ngx-countdown/releases/tag/3.1.0)

**Comment by augustotmw** [comment]
One question:

In version 3.1.0 dont have "format" config option implemented yet?

**Comment by cipchk** [comment]
> 
> 
> One question:
> 
> In version 3.1.0 dont have "format" config option implemented yet?

Abort version 3.x, you can refer to https://github.com/cipchk/ngx-countdown/tree/3.x
