### ISSUE TITLE
When pausing and using {demand: true} is not visible on html, span where numbers should appear is empty with Angular 8

### ISSUE THREAD

**Issue by LoneyGG** [cipchk/ngx-countdown#47]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

In a complete new angular 8 project when pausing or using demand=true countdown won't be visible in html.

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-countdown version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by LoneyGG** [comment]
Found the problem, on commit: e58a5e66e9f5777c5383db32456503f439768e37  you moved the instruction this.reflow(0, true); to the bottom of the onInit function so its never called on pause or on demand so it will never add text.

**Comment by NurGuz23** [comment]
Same issue here, when u resolve ir? Thx

**Comment by NurGuz23** [comment]
> Found the problem, on commit: [e58a5e6](https://github.com/cipchk/ngx-countdown/commit/e58a5e66e9f5777c5383db32456503f439768e37) you moved the instruction this.reflow(0, true); to the bottom of the onInit function so its never called on pause or on demand so it will never add text.

Can u resolve it?

**Comment by LoneyGG** [comment]
> > Found the problem, on commit: [e58a5e6](https://github.com/cipchk/ngx-countdown/commit/e58a5e66e9f5777c5383db32456503f439768e37) you moved the instruction this.reflow(0, true); to the bottom of the onInit function so its never called on pause or on demand so it will never add text.
> 
> Can u resolve it?

Just go back to the previous version / release and you won't encounter the issue

**Comment by cipchk** [comment]
@LoneyGG @NurGuz23 Sorry, i'm too busy, i will fix this in the recent.

**Comment by NurGuz23** [comment]
> @LoneyGG @NurGuz23 Sorry, i'm too busy, i will fix this in the recent.

Thx so much, guy! 

Do u know how many time u could?

**Comment by NurGuz23** [comment]
@cipchk How can I hide the countddown until the countdown begins?
