### ISSUE TITLE
Change the left variable from private to public to working with it.

### ISSUE THREAD

**Issue by gonzalezlrjesus** [cipchk/ngx-countdown#48]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

the variable left in the file countdown.components.d.ts is currently as private

## Expected behavior

Hi guys, i was working with ngx-countdown, but i needed work with the left variable but it was private so i changed it to public. this way i could working with this variable in multiple parts of my code.
## Environment

<pre><code>
Angular version: 8.2.0

ngx-countdown version: 8.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:
<!-- Anything else relevant?  Operating system version, IDE, package manager, HTTP server, ...
 `-->`

`public left;` 

An example of use:
`import { Component, OnInit, ViewChild,  } from '@angular/core';
import { CountdownComponent } from 'ngx-countdown';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  @ViewChild('countdown', { static: true }) counter: CountdownComponent;

  public constructor() {  }

  public ngOnInit() {
          this.counter.left = 15;
  }

}
`

</code></pre>

**Comment by cipchk** [comment]
You can get `left` through the `event` event, but you need settings `notify: 0` inn `config`.

**Comment by gonzalezlrjesus** [comment]
Ok, thank you. what happens is that I working with WebSocket and need change `left `
 time at any time. not only when at zero.
