### ISSUE TITLE
Metadata version mistmatch for module ngx-countdown found version 4, expected 3

### ISSUE THREAD

**Issue by alluk-ghub** [cipchk/ngx-countdown#5]
Hello. I got this error when tried to npm run && ng serve
package.json dependencies
`"dependencies": {
    "@angular/common": "^4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.1.3",
    "@angular/platform-browser": "^4.1.3",
    "@angular/platform-browser-dynamic": "^4.1.3",
    "@angular/platform-server": "^4.1.3",
    "@angular/router": "^4.1.3",
    "angular2-text-mask": "^8.0.1",
    "angular2-uuid": "^1.1.1",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "jquery": "^3.1.1",
    "moment": "^2.13.0",
    "ng-inline-svg": "^4.0.1",
    "ng2-translate": "^5.0.0",
    "ngx-countdown": "1.0.1",
    "ngx-bootstrap": "^2.0.0-beta.2",
    "ngx-pipes": "^1.5.10",
    "rxjs": "^5.1.0",
    "text-mask-addons": "^3.5.1",
    "ts-helpers": "^1.1.1",
    "yargs": "^8.0.2",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.1",
    "@angular/compiler-cli": "^4.3.6",
    "@types/node": "^6.0.42",
    "codelyzer": "~2.0.0-beta.1",
    "dotenv": "^4.0.0",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "^2.0.0",
    "tslint": "~4.4.2",
    "typescript": "~2.3.3"
  }`

**Comment by cipchk** [comment]
please use `"ngx-countdown": "^1.0.1"` if angular5 version.

**Comment by alluk-ghub** [comment]
the same problem with "ngx-countdown": "^1.0.1"

**Comment by cipchk** [comment]
I'm all but certain:

angular5 version: `"ngx-countdown": "^1.0.1"`

angular4 version: `"ngx-countdown": "1.0.2"`

please check your steps and try again.

**Comment by alluk-ghub** [comment]
Checked with both of variants in next way:
1. remove all node_modules
2. npm install --save-dev
3. npm install
4. npm run && ng serve
Result: The same problem. May it depends on some other npm module except angular version? angular-cli maybe or some other.

**Comment by cipchk** [comment]
Also, maybe remove `packagae-lock.json`.

**Comment by alluk-ghub** [comment]
Found the issue. Version 1.0.2 and 1.03 didn't work with angular 4.4.6. Works fine with 4.4.5
