### ISSUE TITLE
Ivy

### ISSUE THREAD

**Issue by hartjo** [cipchk/ngx-countdown#52]
not working in ivy

ERROR Error: Template error: Can't bind to 'ngIf' since it isn't a known property of 'ng-container'.

ERROR Error: Template error: Can't bind to 'ngIf' since it isn't a known property of 'ng-container'.

ERROR Error: Template error: Can't bind to 'ngTemplateOutlet' since it isn't a known property of 'ng-container'.

core.js:6014 ERROR Error: Template error: Can't bind to 'ngTemplateOutlet' since it isn't a known property of 'ng-container'.

**Comment by cipchk** [comment]
Can you provider more information?

**Comment by hartjo** [comment]
Hi, the library is not working if ivy is enabled i got those errors when trying to compile and run the applications

**Comment by cipchk** [comment]
I confirm that I can run in lvy, here are my steps:

1. `ng new ng9` (global `@angular-cli` version is `next`)
2. add `ngx-countdown` module
3. `ng build --prod`

**Comment by hartjo** [comment]
ah see im using angular 8.x.x maybe angular 8 and ivy enabled never going to work after all. i've also seen this error in ngtoastr and they said it will never going work using angular 8.x.x and ivy enabled
