### ISSUE TITLE
Format error when displaying ngx countdown

### ISSUE THREAD

**Issue by anuragd7** [cipchk/ngx-countdown#55]
https://stackblitz.com/edit/ngx-countdown-setup 重现问题
[ x] Bug report 
[x ] Documentation issue or request

## Current behavior
I want to display only hours and minutes in my ngx-countdown. I dont want to display seconds. 
I have set this up as follows in the code below:

html
`<countdown
                    #cd
                    [config]="{ leftTime: leftTime, format: 'h:m', notify: [600, 120] }"
                    (event)="handleEvent($event)"
                  ></countdown>`

The left time is calculated as follows:
ts
`startCountDown(reviewEnd: string) {
    
    const endTime = new Date(reviewEnd);
     const now = new Date();
    if (now < endTime) {
      this.countdownExists = true;
      const endMilliSeconds = endTime.getTime();
      const nowMilliSeconds = now.getTime();
      this.leftTime = (endMilliSeconds - nowMilliSeconds) / 1000;
    }
  }`

The time is now displaying correctly when there is atleast one hour left as below
![image](https://user-images.githubusercontent.com/5083062/69876155-deeae180-12e4-11ea-91d6-aba9e3e0ef1a.png)

However when the time is below 1 hour it shows it incorrectly as 12:22. See pic below
![image](https://user-images.githubusercontent.com/5083062/69876217-09d53580-12e5-11ea-8037-ec7c8a8b5960.png)

## Expected behavior
I would expect the time to be shown as 00:22.

## Environment

Angular version: 8.2.14
ngx-countdown version: 8.0.2

Browser:
- [ ] Chrome (desktop) version 78.0.3904.108

**Comment by DaveOdden** [comment]
Use `HH` or `H` in your format. The link to accepted date/time formats in the documentation is a good reference.

**Comment by anuragd7** [comment]
Thanks that solved it!
