### ISSUE TITLE
Runtime Error Object(...) is not a function

### ISSUE THREAD

**Issue by dheysonalves** [cipchk/ngx-countdown#56]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

When I import the ngx-countdown on a module, I got Object (...) is not a function.
## Expected behavior

It should work properly with basic usage of the dependency.
## Environment

<pre><code>
Angular version: 5.2.11

ngx-countdown version: 8.0.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
Pls use `3.1.0` version, not support angular version `5.x` of latest version.
