### ISSUE TITLE
Autoformat leading 0's?

### ISSUE THREAD

**Issue by TomWaterz** [cipchk/ngx-countdown#57]
Is there a way to auto format and remove the 0's? If there are no days it doesn't show the 00 for days but if there are then it shows the day number?

**Comment by javiersantossanchez** [comment]
> Is there a way to auto format and remove the 0's? If there are no days it doesn't show the 00 for days but if there are then it shows the day number?

Hello @tommhendrick  Yes you can use the prettyText property of CountdownConfig to format your output as you want. 

There is an example to remove the hours when the time is less:  https://stackblitz.com/edit/ngx-countdown-setup-a6rgmo

**Comment by cipchk** [comment]
@tommhendrick May be the [Custom format date](https://cipchk.github.io/ngx-countdown/#/) example is what you want.
