### ISSUE TITLE
Preview with strings

### ISSUE THREAD

**Issue by pearlpandz** [cipchk/ngx-countdown#58]
Will you please add "HH MM SS" string with countdown

**Comment by cipchk** [comment]
Formats a date value, pls refer to [Accepted patterns](https://angular.io/api/common/DatePipe#usage-notes).

BTW, you can also customize the format via [format](https://github.com/cipchk/ngx-countdown/blob/master/src/app/components/demo.component.ts#L21) property.

**Comment by pearlpandz** [comment]
Thanks, I used the same.
