### ISSUE TITLE
How to get the remain time into component

### ISSUE THREAD

**Issue by balreddy-arutla** [cipchk/ngx-countdown#59]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-countdown version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
Are you referring to callbacks?

```html
<countdown [config]="{leftTime: 30, notify: 0}" (event)="onHandleEvent($event)"></countdown>
```
