### ISSUE TITLE
event.left emitted from (event) always showing the same value and it is not updating when called upon

### ISSUE THREAD

**Issue by seetharaghavan** [cipchk/ngx-countdown#61]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ X] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

<countdown #cd1 config = {leftTime: 30} (event)="onHandleEvent($event) />

onHandleEvent($event){
$event.left shows the same 30s and not showing the updated one. 
}

## Expected behavior

$event.left should change 

## Environment

<pre><code>
Angular version: 9

ngx-countdown version: 8.0.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
Pls using `notify` parament, like this:

```html
<countdown [config]="{leftTime: 30, notify: 0}" (event)="onHandleEvent($event)"></countdown>
```
