### ISSUE TITLE
Remaining day is not correct (剩余天数显示错误)

### ISSUE THREAD

**Issue by terryjiang1996** [cipchk/ngx-countdown#63]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
When setting the config to be 
config = {
    "stopTime": new Date('7 April 2020'),
    'format': "d 'd' HH 'h' mm 'm' ss 's'"
}
On the date 6 April 2020, 
The day left (d) will be 1, which should be 0 as the remaining time is less than a day. 
This also applies to the situation when d is larger than 1, it will always be the number it's supposed to be plus 1. 
In https://stackblitz.com/edit/ngx-countdown-setup, if there is a d in format, it will always be 1 bigger than expected. 

## Expected behavior
On the date 6 April 2020, when setting the stopTime being 7 April 2020, d should be 0 instead of 1 if the remaining time is less than 1 day. 

## Environment

<pre><code>
Angular version: 8

ngx-countdown version: 8.0.3

Browser:
All browser. 

Others:

</code></pre>

**Comment by cipchk** [comment]
Pls refer to [More than 24 hours](https://cipchk.github.io/ngx-countdown/#/) demo.

**Comment by terryjiang1996** [comment]
The product requires more than 7 days countdown and using that demo can be too long for display and also confusing the user. Is there a way to fix that?

**Comment by terryjiang1996** [comment]
I got it fixed with that demo, thanks!
