### ISSUE TITLE
how to use it conditionaly with *ngIf

### ISSUE THREAD

**Issue by RiadhBg26** [cipchk/ngx-countdown#64]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-countdown version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
A online [demo](https://stackblitz.com/edit/ngx-countdown-setup-mxuk1n?file=src/app/app.component.ts).
