### ISSUE TITLE
Timer sometimes overruns!

### ISSUE THREAD

**Issue by pete0959** [cipchk/ngx-countdown#68]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Config as follwos:
{ leftTime: 15, format: 's.S', notify: [5], demand:true }

completed action
{action: "done", left: -600, status: 3, text: "59.4"}

## Expected behavior

should go to left:0.0 text: "0.0" and not continue
happens 50% of the time, so really not reliable

## Environment

<pre><code>
Angular version: X.Y.Z

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.41.2

ngx-countdown version: 9.0.1

Browser:
- [x ] Chrome (desktop) version   81.0.4044.113

</code></pre>

**Comment by ferreria23** [comment]
This still happening, it happens in Android when the app is in background.

@pete0959  did you managed to fix this?

**Comment by pete0959** [comment]
> This still happening, it happens in Android when the app is in background.
> 
> @pete0959 did you managed to fix this?

Hi,
No, it's still an issue.

**Comment by cipchk** [comment]
@pete0959 @ferreria23 Sorry, busy at work, try to use version `10.0.2`
