### ISSUE TITLE
Minutes displayed are wrong if your timezone has xx:30 format.

### ISSUE THREAD

**Issue by Panther59** [cipchk/ngx-countdown#69]
When using this timer in timezone which ends with 30 minutes then time remaining is off by 30 mins. It gets done properly. Its just a issue with display minute string.

When I reviewed your code I notice the root cause for this is that you are using getMinutes() instead of getUTCMinutes().

To reproduce this issue just set your machine timezone to anything which ends with 30 minutes. e,g. +0530.

Let me know if you need more information.

Utkarsh Chauhan

**Comment by cipchk** [comment]
ngx-countdown does not use `getMinutes` to get the minutes, but uniformly using `getTime` timestamp, it always uses UTC for time representation, so it does not have a time zone problem.

Can you further use reproduction to explain the issues?

**Comment by Panther59** [comment]
I apologies for confusion, it was issue with another npm package, I accidentally reported here. 

I originally used your npm package but faced some issue hence switched to other npm package where i discovered this problem.

Please ignore this.

**Comment by cipchk** [comment]
May I ask why ngx-countdown can't meet your needs? So I can improve it better.
