### ISSUE TITLE
Help Required.

### ISSUE THREAD

**Issue by belall-shaikh** [cipchk/ngx-countdown#7]
How to hide the hour part if it is 0. 
Currently the hour part is displayed as '00'. 
Can we hide this? It should be only displayed if it is more than 0.

**Comment by cipchk** [comment]
you can set `config.template` property, eg:

```
{
    template: `$!m!-$!s!`
}
```

if you need advanced usage, you can using `repaint` method, a full [demo](https://cipchk.github.io/ngx-countdown/#/tpl).
