### ISSUE TITLE
How to use this timer dynamically for multiple rows

### ISSUE THREAD

**Issue by komalgmore** [cipchk/ngx-countdown#70]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-countdown version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
@komalgmore Sorry, i don't understand what you mean.
