### ISSUE TITLE
ngx timer not resertting to 0 on the date part

### ISSUE THREAD

**Issue by rohit-jagannath** [cipchk/ngx-countdown#71]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
The data part in `<countdown [config]="{ leftTime: 10, format: 'dd:HH:mm:ss' }"></countdown>` is not getting reset to 00 after countdown timer stops.  
Currently it is being displayed as below:
01:00:00:00. 
This will give a wrong impression to end users.
Stackblitz link: https://stackblitz.com/edit/ngx-countdown-setup-mfbxtp

## Expected behavior
The timer should display like below after timer stops.
00:00:00:00. 

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-countdown version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
Your link stackblitz.com/edit/ngx-countdown-setup-mfbxtp seems to be broken, can you fix this?

**Comment by rohit-jagannath** [comment]
@cipchk The link is working fine for me. But this is all i had over there -
<countdown [config]="{ leftTime: 10, format: 'dd:HH:mm:ss' }"></countdown>

**Comment by cipchk** [comment]
@rohit-jagannath Maybe duplcated of #49

**Comment by Blamax** [comment]
I can confirm that this problem still exists. <countdown [config]="{ leftTime: 10, format: 'dd:HH:mm:ss' }"> stops at 01:00:00:00

**Comment by cipchk** [comment]
About more than 24 hours demo via https://github.com/cipchk/ngx-countdown/blob/master/src/app/components/more-than-24-hours.component.ts
