### ISSUE TITLE
ERROR NullInjectorError: StaticInjectorError[t -> t] on deployed server

### ISSUE THREAD

**Issue by rohit-jagannath** [cipchk/ngx-countdown#72]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

I imported the Countdownmodule and started using <countdown> html tag.
Countdown timer works fine when loaded on **localhost:4200**. However, when i deploy the code to server, it throws StaticInjectorError. Screen shots below:

![image](https://user-images.githubusercontent.com/54638684/84215604-63849c80-aa8c-11ea-9103-6cad149d0ed1.png)

## Expected behavior
Should work fine on deployed server

## Environment

<pre><code>
Angular version: 8.0.2

ngx-countdown version: 9.0.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
Pls using `8.0.4` version in angular 8

**Comment by pcf26536** [comment]
Facing the same issue, i quite can't get the fix.

**Comment by rohit-jagannath** [comment]
@cipchk It worked after i downgraded ngxcountdown from 9.x.x to 8.0.4. Thank you. :)

**Comment by pcf26536** [comment]
> @cipchk It worked after i downgraded ngxcountdown from 9.x.x to 8.0.4. Thank you. :)

Thanks for the explanation
