### ISSUE TITLE
Doesn't work when 1d < stopTime < 2d

### ISSUE THREAD

**Issue by db-ruslan** [cipchk/ngx-countdown#74]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

2 days xx hrs

## Expected behavior

Must show 1d xx hrs

## Environment

<pre><code>
Angular version: 10.0.0

ngx-countdown version: 10.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
Pls refer to [More than 24 hours](https://cipchk.github.io/ngx-countdown/#/) demo.

**Comment by db-ruslan** [comment]
The demo doesn't make sense, it should be 1 day XX hours rather than 28 hrs.

**Comment by cipchk** [comment]
This is because the default format string is `HH:mm:ss`, you can changing to `D day - HH:mm:ss`, like this:

```ts
  moreThan24Hours: CountdownConfig = {
    leftTime: 60 * 60 * 28,
    format: `D day - HH:mm:ss`,
    formatDate: ({ date, formatStr }) => {
```

**Comment by db-ruslan** [comment]
The issue is not related to format, it shows incorrect number of days(2) if stopTime is 1.5 days from now.

**Comment by cipchk** [comment]
Can you provide an expected example?
