### ISSUE TITLE
I don't start action hit once timer started

### ISSUE THREAD

**Issue by Shivampio** [cipchk/ngx-countdown#75]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[*] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Once the  the timer started it hits the start action.
## Expected behavior
i don't want start action fired.

## Environment

<pre><code>
Angular version: 8.2.14

ngx-countdown version: 8.0.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
You can using [(event)](https://github.com/cipchk/ngx-countdown#countdown) property.
