### ISSUE TITLE
ERROR in src/app/shared/shared.module.ts(55,3): error TS2741: Property 'locale' is missing in type '{ format: string; }' but required in type 'CountdownGlobalConfig'.

### ISSUE THREAD

**Issue by kurubavinodkumar** [cipchk/ngx-countdown#76]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
getting below error 
ERROR in src/app/shared/shared.module.ts(55,3): error TS2741: Property 'locale' is missing in type '{ format: string; }' but required in type 'CountdownGlobalConfig'.

function countdownConfigFactory(): CountdownGlobalConfig {
  return { format: `mm:ss` };
}

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-countdown version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
Can you provide angular, ngx-countdown versions?

**Comment by kurubavinodkumar** [comment]
@cipchk  thanks for your interest .
please find below details :- 
    angular: 8.1
    ngx-countdown: 10.0.0

**Comment by cipchk** [comment]
@kurubavinodkumar angular8 just only use `8.x` version, the `10.x` only working in angular10.
