### ISSUE TITLE
Bugs when run with --prod

### ISSUE THREAD

**Issue by reynave** [cipchk/ngx-countdown#77]
## Bug Report or Feature Request
<pre><code>
[ x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
just use simple code `<countdown [config]="{ leftTime: 100, format: 'm:s' }"></countdown>`
this bugs happen when I serve with "**ng serve --prod**", same problem after **ng build --prod**
<code>
RROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError[n -> n]: 
  StaticInjectorError(Platform: core)[n -> n]: 
    NullInjectorError: No provider for n!
NullInjectorError: StaticInjectorError[n -> n]: 
  StaticInjectorError(Platform: core)[n -> n]: 
    NullInjectorError: No provider for n!
</code>

but everything work well when I run without --prod

## Environment

<pre><code>
Angular version: 8.2.4
ngx-countdown version: 9.0.1

Browser:
- [ x ] Chrome (desktop) version 84.0.4147.105 (Official Build) (64-bit)
- [ x ] Firefox version latest
- [  ] Safari (desktop) version 
- [ x ] IE version 

</code></pre>

**Comment by cipchk** [comment]
Pls using `8.x`

**Comment by reynave** [comment]
Sorry wrong noted... 

I'm use  ` "ngx-countdown": "^9.0.1",`
