### ISSUE TITLE
Fire event if timer.left < 5 minutes

### ISSUE THREAD

**Issue by mohsen69** [cipchk/ngx-countdown#79]
I want to do something if timer left property was lower than 5 minutes.
Something like this :

```
 <countdown [config]="{demand: true, leftTime: 8000}" (ticks)="onTicks($event)">
        $!m!:$!s!
      </countdown>
```

```
onTicks(event) {
if(event.left <= 5000)
alert('catch');
}
```

How can i do this ?Thanks

**Comment by cipchk** [comment]
You can using `notify: 0`, it will be trigger every time:

```diff
- <countdown [config]="{demand: true, leftTime: 8000}" (ticks)="onTicks($event)">
+ <countdown [config]="{demand: true, leftTime: 8000, notify: 0}" (event)="onTicks($event)">
```

**Comment by mohsen69** [comment]
Thank you so much @cipchk.
I leave a sample for those who want to see final code :

`<countdown [config]="{demand: true, leftTime: 8000, notify: 0}" (event)="onTicks($event)"`

```
onTicks(ev) {
    if (+ev.left <= 300000) //5 minutes
      alert('catch');
  }
```
