### ISSUE TITLE
Pause/resume/stop the counter

### ISSUE THREAD

**Issue by technbuzz** [cipchk/ngx-countdown#8]
How can I pause the counter as well as stop a particular counter and bring all the values to zero.

**Comment by cipchk** [comment]
You can call `restart()`  ([demo](https://github.com/cipchk/ngx-countdown/blob/master/demo/src/app/components/demo.component.ts#L36))

**Comment by technbuzz** [comment]
I solved the **Pause part** by 
```
pauseTimer(){
    this.counter.ngOnDestroy();
  }
```
but I am not proud of it, I think their has to be functionality for this.

**Comment by technbuzz** [comment]
The `restart()` does as it says to restart the timer but doesn't **resume** or **pause** things.

**Comment by technbuzz** [comment]
For now I am good with `ngOnDestroy()`

**Comment by cipchk** [comment]
Your suggestion is good, i will add `pause()` `resume()` methods & eventemmit in component.

Also, i suggestion reopen it.
