### ISSUE TITLE
Example of date-fns usage

### ISSUE THREAD

**Issue by jbakoc1** [cipchk/ngx-countdown#80]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: 9.1.0

ngx-countdown version: 8.0.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
https://github.com/cipchk/ngx-countdown/blob/master/src/app/components/demo.component.ts#L45
