### ISSUE TITLE
countdown component displaying time like -1:10:01:29

### ISSUE THREAD

**Issue by bretbas** [cipchk/ngx-countdown#81]
Hello everyone! 
I have a date `expire`, which i want to pass in your `countdown`. And I do that.
But when the `expire` date is really expired, the `countdown` component display it like this `-1:10:01:29`.
But I want `00:00:00:00`

How can I do that?

**Comment by cipchk** [comment]
It's easy to achieve with `render`, like this:

```html
<countdown [config]="{leftTime: 3}" [render]="renderTpl"></countdown>
<ng-template #renderTpl let-i>
  {{ i.value > 0 ? i.text : 'Finished' }}
</ng-template>
```

**Comment by bretbas** [comment]
@cipchk , Thanks!
