### ISSUE TITLE
Version 8.0.4 not available in git release, but its available in https://www.npmjs.com/package/ngx-countdown/v/8.0.4

### ISSUE THREAD

**Issue by jitu5001** [cipchk/ngx-countdown#82]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-countdown version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
I'm lazy, the version is based on npm, sorry.
