### ISSUE TITLE
can we count up ?

### ISSUE THREAD

**Issue by koraysels** [cipchk/ngx-countdown#83]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-countdown version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
Sorry i don't understand your needs?

**Comment by koraysels** [comment]
Instead of counting down to a date.. counting up from a date untill now.?



Sorry for being brief, sent from my iPhone

**Comment by cipchk** [comment]
Sorry, not support.

**Comment by jek-bao-choo** [comment]
ngx-countdown is for countdown.
For countup use ngx-countUp https://github.com/inorganik/ngx-countUp
