### ISSUE TITLE
How do I count from dd HH mm ss

### ISSUE THREAD

**Issue by SandeepSagarPanjala** [cipchk/ngx-countdown#84]
Want to display counter time from days, hours minutes, and seconds is it possible?

I tried: 
<countdown [config]="{leftTime: 231321312: '$!d!d $!h!h $!m!m $!s!s'}"></countdown>
<countdown [config]="{leftTime: 231321312, format: 'dd hh mm ss'}"></countdown>

none of them are working

**Comment by SandeepSagarPanjala** [comment]
I've been through closed issues and found the solution

**Comment by jereval0x** [comment]
Which closed issue solved your problem?
