### ISSUE TITLE
How to make counter more than 24 hours for example 50:00:00 and not day format?

### ISSUE THREAD

**Issue by omarkamoun1** [cipchk/ngx-countdown#85]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

ngx-countdown version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
[More than 24 hours](https://cipchk.github.io/ngx-countdown/#/)

**Comment by cfmorales** [comment]
> 
> 
> [More than 24 hours](https://cipchk.github.io/ngx-countdown/#/)

Theres no code in your example

**Comment by cipchk** [comment]
@cfmorales https://github.com/cipchk/ngx-countdown/issues/49#issuecomment-561989905
