### ISSUE TITLE
How can i config the countdown dynamically ?

### ISSUE THREAD

**Issue by dangminhbk** [cipchk/ngx-countdown#88]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Current behavior

`                    <countdown class="text-orange text-lg" [config]="{ stopTime: calculateEndTime(item.endTime), format: 'hh:mm:ss'  }">
                    </countdown>`

`
  calculateEndTime(date: Date) {
    return dayjs(date).unix();
  }
`

It seem that the countdown not work, it freeze.

## Environment

<pre><code>
Angular version: 9.1.4

ngx-countdown version: 9.0.1

Browser:
- [x] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>

**Comment by cipchk** [comment]
Like this:

```ts
@Component({
	template: `
		<countdown *ngIf="timeConfig" class="text-orange text-lg" [config]="timeConfig"></countdown>
	`
})
export class DemoComponent implements OnInit {
	timeConfig: CountdownConfig;

	ngOnInit(): void {
		this.timeConfig = { stopTime: this.calculateEndTime(this.item.endTime), format: 'hh:mm:ss' };
	}
}
```

**Comment by dangminhbk** [comment]
> Like this:
> 
> ```ts
> @Component({
> 	template: `
> 		<countdown *ngIf="timeConfig" class="text-orange text-lg" [config]="timeConfig"></countdown>
> 	`
> })
> export class DemoComponent implements OnInit {
> 	timeConfig: CountdownConfig;
> 
> 	ngOnInit(): void {
> 		this.timeConfig = { stopTime: this.calculateEndTime(this.item.endTime), format: 'hh:mm:ss' };
> 	}
> }
> ```

Thanks you!
