### ISSUE TITLE
Start the counter on demand (on button click)

### ISSUE THREAD

**Issue by technbuzz** [cipchk/ngx-countdown#9]
Is there a way to start the counter on click not on component load.?

**Comment by cipchk** [comment]
Not yet, you can `*ngIf` via fixed variable.

**Comment by smallswan399** [comment]
@cipchk I got the same issue here
*ngIf you mean that show or hide completely the countdown depend on the *ngIf expression value?
I think it is better the component support to show the time left on init and Start the counter on demand (on button click)
