### ISSUE TITLE
Is there a way to display timeLeft >1 hr in mm:ss format ?

### ISSUE THREAD

**Issue by KeshavKundal** [cipchk/ngx-countdown#99]
Is there a way to display timeLeft>1hr in mm:ss format ?

Example: If timeLeft is 3900 ie 65 mins, can we display it in mm:ss format as 65:00 and start countdown from there, Instead of having 65 mins as 01:05:00 in hh:mm:ss format.

**Comment by cipchk** [comment]
Yes, you can custom format data via `formatDate`, like this: https://github.com/cipchk/ngx-countdown/blob/master/src/app/components/demo.component.ts#L31

**Comment by KeshavKundal** [comment]
@cipchk Can you please share a working demo for this? That will work wonders.

**Comment by keshav929** [comment]
I figured out the solution for this problem. Thanks @cipchk  for pointing me in the right direction.
Here is the Solution demo URL for this issue: https://stackblitz.com/edit/ngx-countdown-demo-morethan59hours?file=src/app/app.component.ts
